[package]
name = "doorui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19"
crossterm = "0.25"
rusqlite = {version="0.28.0", features=["chrono"]}
chrono = "0.4.22"